### ISSUE TITLE
Roadmap to Publishing

### ISSUE THREAD

**Issue by SeeminglyScience** [SeeminglyScience/PSESHelperLibrary#19]
This list is a work in progress, suggestions are very welcome.

# Planned

- [ ] Rename the module.  Leaning towards AuthorTools, but definitely open to suggestions.

- [x] Add Test-ScriptExtent for extent position testing.  Include options for after, before, and within.

- [x] Add Get-Token function to get tokens from an extent.  This is needed to commands that alter things like if statements, or comments.

- [x] Refactor project structure for a mix of PowerShell and C#

- [ ] Port *at least* the `PSEditorCommand` class to C#.  This is the only "public" class of the module at the moment, so it's the only one that would be a breaking change if a namespace was added.

- [x] Remove comment based help in favor of markdown generated MAML.

- [ ] Write README with build instructions and contribution instructions.

- [x] Write a new build script that uses `InvokeBuild`.

- [ ] Replace ConvertTo/From-ScriptExtent functions with a PSTypeConverter.

# Decisions

- [ ] Move all editor commands to separate projects as themed command packs?  Or just have one monolithic module?

- [ ] Start at version 0.1.0 or 1.0.0?

- [ ] Should `PSStringTemplate` be packaged with this module to reduce nested dependencies?

# Nice to have

- [ ] Port all PowerShell classes to C#

- [ ] Examples folder with interactive demos.

**Comment by daviwil** [comment]
Hey Patrick!  I haven't had much time to dig into what you've been doing lately but I think we should probably discuss some API details before you ship your first public release.  I want to make sure that the improvements I'm working on right now won't break you.  I'd also like to see if there's anything useful you could contribute over to PSES :)

Regarding naming, what's the overall goal of this module?  I'd certainly like to help you come up with a good name that helps people understand what it's useful for.

I'm looking forward to promoting this when you release it :)

**Comment by SeeminglyScience** [comment]
Hey David, thanks for checking in!

The main goal of the module depends on if I split the editor commands into separate projects.  At it's core the goal of the module is to provide tools that make creating editor commands (and interacting with the editor in general) easier.  The bulk of the non-editor command functions are tools for finding or manipulating asts/tokens/extents, etc.  

That's my current plan, to have this module be a base for packs of similarly themed editor commands (like a command pack for manipulating manifests, one for generating classes, etc)

The alternative would be to keep it how it is and just keep adding editor commands to it.  That would make this more like a ISESteroids alternative, but harder for other people to build off.

> I'd also like to see if there's anything useful you could contribute over to PSES :)

Yeah, definitely!  I need to go over everything and see what makes sense for PSES or PSSA (and can be made compatible with PowerShell 3.0 or ported to C# without too much trouble).  In the mean time, if you see anything come through that catches your eye definitely let me know!

> I'm looking forward to promoting this when you release it :)

I'm looking forward to that too! Really though I greatly appreciate that, thank you :)

**Comment by daviwil** [comment]
Just a quick note about something I want to do soon: I'm planning to make a submodule of PSES that gets loaded inside of the editor session's runspace to expose commands that are useful inside of the editor.  That's also where I'd be putting extension commands that should be registered every time the editor starts up.  I think many of your functions would be really useful there!

Having a hard time thinking of what to call it though.  PowerShellEditorServices.Internal is accurate but uninteresting.  PowerShellEditorServices.Commands?

**Comment by SeeminglyScience** [comment]
Perfect timing, I was going over how the current functions are loaded and was about to reach out about making some more :)

For the name, I like Commands the best of the two.  If you aren't set on one word I think InternalCommands is better, or maybe BuiltInCommands.  I also like Tools, but that may be a little vague.  I'll keep thinking about it.

Also in another thread I saw you mention a PowerShell module that creates text from templates.  I know you were referring to Plaster, but I thought I'd mention that use case is exactly what I made my other project, [PSStringTemplate](https://github.com/SeeminglyScience/PSStringTemplate) for. That being said, the license for the library it's based on is BSD 3-Clause so I'm not sure if that's even something that could be integrated.
